language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_1af118d8ec09_key -iv $encrypted_1af118d8ec09_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

after_success:
  - test $TRAVIS_BRANCH == "master" && shipit production deploy